### ISSUE TITLE
Failed to parse json

### ISSUE THREAD

**Issue by irisava** [Azure-Samples/azure-iot-samples-node#12] opened 2018-06-19 20:20 UTC
### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>1

### Any log messages given by the failure
>npm install
npm ERR! file C:\Users\xxx\OneDrive -xxx\azure-iot-samples-node-master\iot-hub\Tutorials\ConnectivityTests\package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected token } in JSON at position 714 while parsing near '...e-mqtt": "1.4.1",
npm ERR!   }
npm ERR! }
npm ERR! '
npm ERR! File: C:\Users\xxx\OneDrive - xxx\azure-iot-samples-node-master\iot-hub\Tutorials\ConnectivityTests\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! Tell the package author to fix their package.json file. JSON.parse

### Expected/desired behavior
> can run the package.json

### OS and Version?
> Windows 10

### Versions
> Windows 10

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pierreca** [comment] 2018-06-27 00:43
There seems to be nothing wrong with the package.json file checked in our repository. Can you double-check on your end if it was downloaded correctly?

Feel free to post the content that you have here for us to take a look at. in the meantime, closing the issue since I could not reproduce it. I was able to download and parse the package.json file properly.

**Closed by pierreca** 2018-06-27 00:43 UTC
